### ISSUE TITLE
Tweak Dependabot Config

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/unified-graphics#200]
## Problem

The version update PRs that Dependabot submits are quite noisy. (>10 PRs/week)

## Solution

Reduce Dependabot version updates to once a month. Explore auto-merging minor & patch versions. Potentially, we could look into auto-merging updates depending on if they're dev or production dependencies.

## No Gos

Auto-merging major version updates. 

## Rabbit Holes

_Describe any solutions to problems that pose a risk to completing this project on time._

**Comment by esheehan-gsl** [comment]
@ian-noaa I was hoping that once we got caught up, this wouldn’t be so bad, but it seems like we’re pretty consistently having 7–10 updates a week. I think I‘m in favor of taking this out of shaping and changing the frequency to once a month, since none of these updates seem that important.

**Comment by ian-noaa** [comment]
Sounds good. I'll go ahead and do that. If we want to do auto-merging for particular classes of dependencies I could explore that in a different PR.
