### ISSUE TITLE
Our services run as root in their containers

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/unified-graphics#303]
## Describe the bug

While debugging a different issue, VLab & I discovered our services are running as root inside our docker images. This is a security risk and not a best practice.

## To Reproduce

1. Run a container: `docker run --rm -it --entrypoint bash ghcr.io/noaa-gsl/unified-graphics/ui:main`
2. Be granted root access

## Expected behavior

The containers shouldn't be running as root.

## Additional context

VLab uses `securityContext.runAsNonRoot: true` in their k8s manifests to disallow images with the root user. We should do something similar in our manifests.

**Comment by esheehan-gsl** [comment]
Oops. We can get this fixed pretty quickly.
