### ISSUE TITLE
Zarr groups without minutes in the timestamp can’t be found

### ISSUE THREAD

**Issue by esheehan-gsl** [NOAA-GSL/unified-graphics#345]
## Describe the bug

At some point we lost the minute-level precision in our timestamps. So instead of `2023-06-02T17:00` we have `2023-06-02T17` in the Zarr group. When we create the `<select>` element for the initialization time, we have no way of knowing how much precision was in the ingested NetCDF file and thus no idea whether the minutes were included in the group path or not, so we assume minute-level precision in the timestamp. This means that any analysis stored without the minutes in the initialization time will always 404 in the application.

## To Reproduce

1. Go to https://unified-graphics.noaa.gov/?model=RTMA&system=WCOSS&domain=CONUS&frequency=REALTIME&background=RRFS&initialization_time=2023-06-02T17%3A00&variable=ps
2. None of the charts load
3. Remove the `%3A00` from the `initialization_time` parameter in the URL
4. Load the page
5. The charts load

## Expected behavior

URLs generated by submitting the “Select Data” form should load.

**Comment by esheehan-gsl** [comment]
I think the best solution here is to enforce uniform group names in our Zarr. We can accommodate different filename formats for the NetCDF files we ingest, but we should make sure our output is uniform and doesn’t depend on how the ingested file names are formatted.

So I think we should always write out the group names with minutes. If the minutes are missing in the ingested file name, we can just assume `:00`. We’ll also want to do a bulk rename on the existing groups that are missing minutes in the name.

**Comment by ian-noaa** [comment]
That sounds logical to me. I'll work on a standalone script to rename the existing groups with missing minutes.
