### ISSUE TITLE
Document log access

### ISSUE THREAD

**Issue by esheehan-gsl** [NOAA-GSL/unified-graphics#407]
Because we’re running everything in AWS, access to the logs is not as straightforward as simply SSH’ing into a server and `cat`’ing some log files. We have two different applications—the web application and the Lambda ingest pipeline—that generate logs, and those logs are in different places.

We should document how to access these logs to make debugging issues in production easier.

**Comment by ian-noaa** [comment]
I'm thinking of putting this documentation in the `CONTRIBUTING.md` or in a separate `docs/*.md` file. Do you have any thoughts on where it goes?

**Comment by esheehan-gsl** [comment]
`CONTRIBUTING.md` seems like a good place. I think maybe our docs need to grow beyond that (perhaps the wiki here, for starters), but for now this is a good place to get them down.
