### ISSUE TITLE
Time Series Visualization of Obs - Guess

### ISSUE THREAD

**Issue by esheehan-gsl** [NOAA-GSL/unified-graphics#44]
## Problem

Display time series for model diagnostics that show the average $Obs - Guess$ for both the first and third loops for multiple model initializations. (First line chart in the example below.)

![Four time series showing observation assimilation statistics over a period of a month](https://user-images.githubusercontent.com/85259329/166700015-56a2a5c5-5962-4c15-84e5-7552fa4405e9.png)

## Solution

TBD

## No Gos

For now we’ll focus on showing the average $Obs - Guess$ for both minimization loops and not worry about distinguishing between used and monitored observations or showing the root mean square of the observations.

## Rabbit Holes

If we need to read this data from multiple NetCDF files generated by multiple model runs, we will most likely want to consolidate this data in some form (possibly Zarr). For this issue, it is enough to manually generate that consolidated file. We can investigate a data transformation pipeline at another time.

**Comment by terraladwig** [comment]
Yes, multiple diag files will be needed for this capability.  
There is growing interest in this capability.  Both for an average O-B and for individual stations. 

A similar but slightly different type of time series plot would be to visualize actual O and B values. Here is an example where individual model grid point values are plotted and compared to observation values for several times.
<img width="585" alt="ob_plot_coastline" src="https://user-images.githubusercontent.com/51802865/215942332-8421fd37-323f-46fe-abfe-58d29bab8ad1.png">

**Comment by davidturner53** [comment]
Terra,

   The actual O and B values are included in the diag files?  That is
cool.  Would you be able to point me to one of the diag netCDF files please?

   thanks,
Dave

**Comment by guoqing-noaa** [comment]
Dave, 

You can find diag netCDF files under rrfs_b or rtma_b real-time runs. Here is an example:
/lfs4/BMC/nrtrr/NCO_dirs/v0.3.2/com/RRFS_conus_3km.20230130/20/diag*.nc4

For 187/188 temperature, the O is a modified value after terrain matching. 

Guoqing

**Comment by terraladwig** [comment]
My understanding is that the grid point B values in the example I shared would NOT be in the diag files.  I think they would have to be pulled out of the gridded background data itself.  Having to pull data from the large model files may not be a practical thing to do next, but we may want to do it in the future. So maybe that is a connected, but new issue.   Time series of the o-b and o data from the diag files are a higher priority.
