### ISSUE TITLE
Data processing pipeline

### ISSUE THREAD

**Issue by esheehan-gsl** [NOAA-GSL/unified-graphics#67]
## Problem

The diagnostic data that is output from the models is not organized in a way that is the most efficient for use in an interactive application.

## Solution

We should pre-process the NetCDF files into a format that is faster to read and requires less processing on requests from the user interface.

- Combine NetCDF files into a single Zarr array (should be easier to access from an S3 bucket)
- Make use of coordinates shared across variables
- Convert vectors from $(u, v)$ format to a direction and magnitude

### Zarr Structure

We’ll use [groups](https://zarr.readthedocs.io/en/stable/tutorial.html#groups) in the Zarr array to help organize the data and make it easy to process NetCDF files in parallel. We’ll group by model (RRFS or 3DRTMA), then the model initialization time (YYYYMMDDTHHMM), and then variable (temperature, wind, pressure, moisture).

The first and third minimization loops are stored in separate NetCDF files, but we’ll combine them into a single Zarr array using the loop (guess or analysis) as one set of [coordinates](https://docs.xarray.dev/en/stable/user-guide/data-structures.html) for the values in the array. This may mean that we can’t process the `anl` and `ges` files in parallel, but I think if we can configure Zarr to [chunk](https://zarr.readthedocs.io/en/stable/tutorial.html#persistent-arrays) along that dimension, we may still be able to run these in parallel.

### Pre-calculating Vector Values

Vector variables are stored in $(u, v)$ components, but we typically want to work with these in terms of the vector’s magnitude and direction (polar coordinates) so we’ll do these calculations when we ingest any vector variables to save on computation in the backend.

There are six variables that define the vectors in a diagnostics file: `Observation`, `Obs_Minus_Forecast_adjusted`, and `Obs_Minus_Forecast_unadjusted`; there is one of each of these for both `u_` and `v_`. We will pass these six variables through and store them in the Zarr, but we will also calculate `Observation_magnitude`, `Observation_direction`, `Obs_Minus_Forecast_magnitude_adjusted`, `Obs_Minus_Forecast_direction_adjusted`, `Obs_Minus_Forecast_magnitude_unadjusted`, `Obs_Minus_Forecast_direction_unadjusted`.

In order to calculate our magnitude and direction for `Obs_Minus_Forecast`, we don’t want to use the existing `u_Obs_Minus_Forecast` and `v_Obs_Minus_Forecast` vector components, because we’ll lose the sign on the difference — <i>i.e.</i> we won’t be able to tell whether the forecast overestimated the magnitude and direction, or underestimated them.

```python
u_Forecast_adjusted = dataset["u_Observation"] - dataset["u_Obs_Minus_Forecast_adjusted"]
v_Forecast_adjusted = dataset["v_Observation"] - dataset["v_Obs_Minus_Forecast_adjusted"]
u_Forecast_unadjusted = dataset["u_Observation"] - dataset["u_Obs_Minus_Forecast_unadjusted"]
v_Forecast_unadjusted = dataset["v_Observation"] - dataset["v_Obs_Minus_Forecast_unadjusted"]
```

From here we can calculate the magnitude and direction for the `u_` and `v_` components of the observations and the forecasts (adjusted and unadjusted).

```python
magnitude = numpy.sqrt(u**2 + v**2)
direction = (90 - numpy.degrees(numpy.arctan2(-v, -u))) % 360
```

And then we can subtract the magnitude and direction of the forecasts (adjusted and unadjusted) from the observation magnitude and direction and store that.

### Observation Coordinates

The `Longitude` values stored in the NetCDF diag files are [degrees East](https://github.com/NOAA-GSL/unified-graphics/discussions/25#discussioncomment-3262243), so they range from about 225°–299°E, but for mapping in the UI, we prefer a range of -180°–180°, where negative values represent degrees West. So when we store the longitude, we can rewrite this value.

```python
longitude = xarray.where(
    dataset["Longitude"] > 180,
    dataset["Longitude"] - 360,
    dataset["Longitude"]
)
```

### Time series

For now we won’t worry about time series data, which may actually benefit from being stored in a separate Zarr with a different format (#44).

### Coordinates and dimensions

It’s tempting to add additional coordinates to the xarray Dataset such as `Station_ID` and `Time`. For the time-being, however, it’s probably best to leave these as variables unless we’re able to confirm that we’ll derive some benefit from converting these to coordinates.

### Triggering the pipeline

Ideally, this should be triggered by an event in S3 that notifies us when there are new files to add, but for now it is acceptable to either poll for new data, or simply run the pipeline manually to generate some test data for development.

### Archives

We’ll probably want to limit the size of this store somehow and archive old data, rather than deleting it. But for now, we’ll just delete data if the bucket starts getting too expensive.

**Comment by esheehan-gsl** [comment]
@ian-noaa feel free to lean on me as much as you’d like on this. I’ve been spending a fair amount of time with these diag files over the last 12 weeks, and I’ve tried to include the relevant discoveries here, but I’m happy to go into more detail if anything’s unclear. My knoweldge of both xarray and Zarr is still fairly basic, so we may be stumbling through some of that together. 😅

And if you’re finding that you don’t really have time for this one, just kick it back over to me.

**Comment by esheehan-gsl** [comment]
@ian-noaa I’ve started looking into setting up a Lambda function to handle this. One thing I noticed right away is that I lack permissions on s3://parallelcluster-rtma-cluster to configure event notifications for the bucket. We’ll need a notification from S3 anytime a new NetCDF file is uploaded to trigger our pipeline. If you have permissions to configure events, then I think we’re all set. Otherwise we’ll need to find out if we can get permissions, or whom we have to ask to configure the event for us.

**Comment by ian-noaa** [comment]
Sounds good. VLab retains all the permissions for AWS resources so we'll have to go through Bryan for this. Did you want the notification to go directly to the lambda function or were you thinking of putting an SQS (queue) or SNS (pub/sub) service in the middle?

Publishing directly to the lambda function seems like the easiest way to start.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html

**Comment by esheehan-gsl** [comment]
I don’t know anything about SQS or SNS. Is there a reason we’d want those as intermediaries? Is this a load balancing thing? Since the models only run once an hour, I was expecting that we’d have maybe 6–12 files to process once an hour, which doesn’t seem like something we’d need a queue for, but maybe that’s naïve.

**Comment by ian-noaa** [comment]
I think sending the notification directly to Lambda is the place to start. If we wanted anything more, SQS would probably be the one to look at.

It sounds like notifications to lambda events aren't guaranteed to be received - if for some reason Lambda doesn't handle the event, it's discarded.

For us, the advantage of SQS is that it would let us get more control over retries in case a message wasn't received or processing failed for whatever reason.

SNS's main advantage would be it would let multiple consumers act on the same event.

**Comment by esheehan-gsl** [comment]
I like the idea of not introducing additional services if we don’t need them. So if the issue with going straight to Lambda without a queue is that we might lose some events, I wonder how we can monitor the situation so that we know if we’re dropping events.

**Comment by ian-noaa** [comment]
I agree. 

Lambda apparently retries events 2 times after a failure and keeps events for 6 hours, after which they're discarded. If we wanted to add retries later, Lambda can be set up with a "Dead Letter Queue" (DLQ) but that requires an SQS/SNS feed to publish to. 

As to monitoring so we're aware that events were dropped - I wonder if CloudWatch would have the ability to at least let us know. Otherwise, the DLQ with SQS would be the way to go.
